'use strict';

// Oxlint plugin port of eslint-plugin-storybook (MIT).
// The JavaScript layer adapts Oxlint's ESLint-compatible plugin API; Storybook
// AST analysis and fix range calculation run in Rust through Oxc.

const fs = require('node:fs');
const path = require('node:path');

const { eslintCompatPlugin } = require('@oxlint/plugins');
const { implementedStorybookRuleNames, scanStorybook } = require('./api.js');

const PLUGIN_NAME = 'storybook';
const DOCS_BASE =
  'https://github.com/storybookjs/storybook/blob/next/code/lib/eslint-plugin/docs/rules';
const diagnosticsCache = new WeakMap();

const storyFiles = ['**/*.stories.@(ts|tsx|js|jsx|mjs|cjs)', '**/*.story.@(ts|tsx|js|jsx|mjs|cjs)'];

const csfRuleConfig = Object.freeze({
  'csf-component': 'warn',
  'default-exports': 'error',
  'hierarchy-separator': 'warn',
  'no-redundant-story-name': 'warn',
  'story-exports': 'error',
});

const csfStrictRuleConfig = Object.freeze({
  ...csfRuleConfig,
  'no-stories-of': 'error',
  'no-title-property-in-meta': 'error',
});

const addonInteractionsRuleConfig = Object.freeze({
  'await-interactions': 'error',
  'context-in-play-function': 'error',
  'use-storybook-expect': 'error',
  'use-storybook-testing-library': 'error',
});

const recommendedRuleConfig = Object.freeze({
  'await-interactions': 'error',
  'context-in-play-function': 'error',
  'default-exports': 'error',
  'hierarchy-separator': 'warn',
  'no-redundant-story-name': 'warn',
  'no-renderer-packages': 'error',
  'prefer-pascal-case': 'warn',
  'story-exports': 'error',
  'use-storybook-expect': 'error',
  'use-storybook-testing-library': 'error',
});

const configRuleOnly = (ruleConfig) =>
  Object.fromEntries(
    Object.entries(ruleConfig).map(([ruleName, config]) => [`${PLUGIN_NAME}/${ruleName}`, config]),
  );

const messages = Object.freeze({
  'await-interactions': {
    interactionShouldBeAwaited: 'Interaction should be awaited: {{method}}',
    fixSuggestion: 'Add `await` to method',
  },
  'context-in-play-function': {
    passContextToPlayFunction: 'Pass a context when invoking play function of another story',
  },
  'csf-component': {
    missingComponentProperty: 'Missing component property.',
  },
  'default-exports': {
    shouldHaveDefaultExport: 'The file should have a default export.',
    fixSuggestion: 'Add default export',
  },
  'hierarchy-separator': {
    useCorrectSeparators: 'Use correct separators',
    deprecatedHierarchySeparator:
      'Deprecated hierarchy separator in title property: {{metaTitle}}.',
  },
  'meta-inline-properties': {
    metaShouldHaveInlineProperties: 'Meta should only have inline properties: {{property}}',
  },
  'meta-satisfies-type': {
    metaShouldSatisfyType: 'CSF Meta should use `satisfies` for type safety',
  },
  'no-redundant-story-name': {
    removeRedundantName: 'Remove redundant name',
    storyNameIsRedundant:
      'Named exports should not use the name annotation if it is redundant to the name that would be generated by the export name',
  },
  'no-renderer-packages': {
    noRendererPackages:
      'Do not import renderer package "{{rendererPackage}}" directly. Use a framework package instead (e.g. {{suggestions}}).',
  },
  'no-stories-of': {
    doNotUseStoriesOf: 'storiesOf is deprecated and should not be used',
  },
  'no-title-property-in-meta': {
    removeTitleInMeta: 'Remove title property from meta',
    noTitleInMeta: 'CSF3 does not need a title in meta',
  },
  'no-uninstalled-addons': {
    addonIsNotInstalled:
      'The {{ addonName }} is not installed in {{packageJsonPath}}. Did you forget to install it or is your package.json in a different location?',
  },
  'prefer-pascal-case': {
    convertToPascalCase: 'Use pascal case',
    usePascalCase: 'The story should use PascalCase notation: {{name}}',
  },
  'story-exports': {
    shouldHaveStoryExport: 'The file should have at least one story export',
    shouldHaveStoryExportWithFilters:
      'The file should have at least one story export. Make sure the includeStories/excludeStories you defined are correct, otherwise Storybook will not use any stories for this file.',
    addStoryExport: 'Add a story export',
  },
  'use-storybook-expect': {
    useExpectFromStorybook:
      'Do not use global expect directly in the story. You should import it from `@storybook/test` (preferrably) or `@storybook/jest` instead.',
  },
  'use-storybook-testing-library': {
    updateImports: 'Update imports',
    dontUseTestingLibraryDirectly:
      'Do not use `{{library}}` directly in the story. You should import the functions from `storybook/test` instead.',
  },
});

const ruleDescriptions = Object.freeze({
  'await-interactions': 'Interactions should be awaited',
  'context-in-play-function': 'Pass a context when invoking play function of another story',
  'csf-component': 'The component property should be set',
  'default-exports': 'Story files should have a default export',
  'hierarchy-separator': 'Deprecated hierarchy separator in title property',
  'meta-inline-properties': 'Meta should only have inline properties',
  'meta-satisfies-type': 'Meta should use `satisfies Meta`',
  'no-redundant-story-name': 'A story should not have a redundant name property',
  'no-renderer-packages': 'Do not import renderer packages directly in stories',
  'no-stories-of': 'storiesOf is deprecated and should not be used',
  'no-title-property-in-meta': 'Do not define a title in meta',
  'no-uninstalled-addons':
    'This rule identifies storybook addons that are invalid because they are either not installed or contain a typo in their name.',
  'prefer-pascal-case': 'Stories should use PascalCase',
  'story-exports': 'A story file must contain at least one story export',
  'use-storybook-expect':
    'Use expect from `@storybook/test`, `storybook/test` or `@storybook/jest`',
  'use-storybook-testing-library': 'Do not use testing-library directly on stories',
});

const ruleTypes = Object.freeze({
  'await-interactions': 'problem',
  'context-in-play-function': 'problem',
  'csf-component': 'suggestion',
  'default-exports': 'problem',
  'hierarchy-separator': 'problem',
  'meta-inline-properties': 'problem',
  'meta-satisfies-type': 'problem',
  'no-redundant-story-name': 'suggestion',
  'no-renderer-packages': 'problem',
  'no-stories-of': 'problem',
  'no-title-property-in-meta': 'problem',
  'no-uninstalled-addons': 'problem',
  'prefer-pascal-case': 'suggestion',
  'story-exports': 'problem',
  'use-storybook-expect': 'suggestion',
  'use-storybook-testing-library': 'suggestion',
});

const fixableRules = new Set([
  'await-interactions',
  'default-exports',
  'hierarchy-separator',
  'meta-satisfies-type',
  'no-redundant-story-name',
  'no-title-property-in-meta',
  'prefer-pascal-case',
  'use-storybook-testing-library',
]);

const implementedRuleNames = Object.freeze(implementedStorybookRuleNames());
const rules = Object.freeze(
  Object.fromEntries(
    implementedRuleNames.map((ruleName) => [ruleName, createStorybookRule(ruleName)]),
  ),
);

const plugin = eslintCompatPlugin({
  meta: {
    name: PLUGIN_NAME,
    version: '0.0.0',
  },
  rules,
  rulesConfig: Object.fromEntries(implementedRuleNames.map((ruleName) => [ruleName, 0])),
  configs: {
    csf: legacyConfig(csfRuleConfig, true),
    'csf-strict': legacyConfig(csfStrictRuleConfig, true),
    'addon-interactions': legacyConfig(addonInteractionsRuleConfig, false),
    recommended: legacyConfig(recommendedRuleConfig, true),
    'flat/csf': flatConfig('csf', csfRuleConfig, true),
    'flat/csf-strict': flatConfig('csf-strict', csfStrictRuleConfig, true),
    'flat/addon-interactions': flatConfig('addon-interactions', addonInteractionsRuleConfig, false),
    'flat/recommended': flatConfig('recommended', recommendedRuleConfig, true),
  },
});

plugin.implementedStorybookRuleNames = implementedRuleNames;
plugin.scanStorybook = scanStorybook;

function legacyConfig(ruleConfig, includeMainConfig) {
  const overrides = [
    {
      files: storyFiles,
      rules: configRuleOnly(ruleConfig),
    },
  ];
  if (includeMainConfig) {
    overrides.push({
      files: ['.storybook/main.@(js|cjs|mjs|ts)'],
      rules: {
        'storybook/no-uninstalled-addons': 'error',
      },
    });
  }
  return { plugins: [PLUGIN_NAME], overrides };
}

function flatConfig(name, ruleConfig, includeMainConfig) {
  const configs = [
    {
      name: `${PLUGIN_NAME}/${name}`,
      files: storyFiles,
      plugins: [PLUGIN_NAME],
      rules: configRuleOnly(ruleConfig),
    },
  ];
  if (includeMainConfig) {
    configs.push({
      name: `${PLUGIN_NAME}/${name}-main`,
      files: ['.storybook/main.@(js|cjs|mjs|ts)'],
      plugins: [PLUGIN_NAME],
      rules: {
        'storybook/no-uninstalled-addons': 'error',
      },
    });
  }
  return configs;
}

function createStorybookRule(ruleName) {
  return {
    meta: {
      type: ruleTypes[ruleName],
      docs: {
        description: ruleDescriptions[ruleName],
        category: 'Storybook',
        recommended: recommendedRuleConfig[ruleName] !== undefined,
        url: `${DOCS_BASE}/${ruleName}.md`,
      },
      fixable: fixableRules.has(ruleName) ? 'code' : undefined,
      hasSuggestions: fixableRules.has(ruleName) ? true : undefined,
      messages: messages[ruleName],
      schema: schemaForRule(ruleName),
    },
    createOnce(context) {
      return {
        Program() {
          for (const diagnostic of diagnosticsForRule(context, ruleName)) {
            reportDiagnostic(context, diagnostic);
          }
        },
      };
    },
  };
}

function schemaForRule(ruleName) {
  if (ruleName === 'meta-inline-properties') {
    return [
      {
        type: 'object',
        properties: {
          csfVersion: { type: 'number' },
        },
        additionalProperties: false,
      },
    ];
  }
  if (ruleName === 'no-uninstalled-addons') {
    return [
      {
        type: 'object',
        properties: {
          packageJsonLocation: { type: 'string' },
          ignore: { type: 'array', items: { type: 'string' } },
        },
        additionalProperties: false,
      },
    ];
  }
  return [];
}

function diagnosticsForRule(context, ruleName) {
  return diagnosticsForContext(context, scanOptionsForRule(context, ruleName)).filter(
    (diagnostic) => diagnostic.ruleName === ruleName,
  );
}

function diagnosticsForContext(context, options) {
  const sourceCode = context.sourceCode ?? context.getSourceCode?.() ?? {};
  const sourceText = sourceTextForContext(context);
  const filename = context.filename ?? context.getFilename?.() ?? 'file.stories.tsx';
  const key = JSON.stringify(options);
  let sourceCache = diagnosticsCache.get(sourceCode);

  if (!sourceCache) {
    sourceCache = new Map();
    diagnosticsCache.set(sourceCode, sourceCache);
  }

  const cached = sourceCache.get(key);
  if (cached && cached.sourceText === sourceText && cached.filename === filename) {
    return cached.diagnostics;
  }

  const diagnostics = scanStorybook(sourceText, filename, options);
  sourceCache.set(key, { sourceText, filename, diagnostics });
  return diagnostics;
}

function scanOptionsForRule(context, ruleName) {
  const scanOptions = { ruleNames: [ruleName] };
  if (ruleName !== 'no-uninstalled-addons') {
    return scanOptions;
  }

  const options = mergeOptions(context.options);
  const packageJsonLocation =
    typeof options.packageJsonLocation === 'string' && options.packageJsonLocation.length > 0
      ? options.packageJsonLocation
      : './package.json';
  const packageJsonPath = path.resolve(packageJsonLocation);
  const installedAddons = readInstalledAddons(packageJsonPath);

  scanOptions.installedAddons = installedAddons;
  scanOptions.ignoredAddons = Array.isArray(options.ignore)
    ? options.ignore.filter((value) => typeof value === 'string')
    : [];
  scanOptions.packageJsonPath = packageJsonPath;
  return scanOptions;
}

function mergeOptions(options) {
  if (!Array.isArray(options)) {
    return {};
  }
  return Object.assign({}, ...options.filter((option) => option && typeof option === 'object'));
}

function readInstalledAddons(packageJsonPath) {
  try {
    const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
    return [
      ...Object.keys(packageJson.dependencies || {}),
      ...Object.keys(packageJson.devDependencies || {}),
    ];
  } catch {
    return [];
  }
}

function sourceTextForContext(context) {
  const sourceCode = context.sourceCode ?? context.getSourceCode?.() ?? {};
  if (typeof sourceCode.getText === 'function') {
    return sourceCode.getText();
  }
  if (typeof sourceCode.text === 'string') {
    return sourceCode.text;
  }
  return '';
}

function reportDiagnostic(context, diagnostic) {
  const report = {
    messageId: diagnostic.messageId,
    data: compactData(diagnostic.data),
    loc: {
      start: {
        line: diagnostic.loc.startLine,
        column: diagnostic.loc.startColumn,
      },
      end: {
        line: diagnostic.loc.endLine,
        column: diagnostic.loc.endColumn,
      },
    },
  };

  if (Array.isArray(diagnostic.fixes) && diagnostic.fixes.length > 0) {
    report.fix = (fixer) => {
      const fixes = diagnostic.fixes.map((fix) =>
        fixer.replaceTextRange([fix.start, fix.end], fix.replacement),
      );
      return fixes.length === 1 ? fixes[0] : fixes;
    };
  }

  context.report(report);
}

function compactData(data) {
  const out = {};
  for (const [key, value] of Object.entries(data || {})) {
    if (value != null) {
      out[key] = value;
    }
  }
  return out;
}

module.exports = plugin;
module.exports.default = plugin;
module.exports.implementedStorybookRuleNames = implementedRuleNames;
module.exports.scanStorybook = scanStorybook;
