// Replays the committed upstream postgresql-eslint-parser fixtures (generated by
// `pnpm run port:tests:postgresql-parser`) against the Rust-backed parser and
// asserts byte-for-byte parity on the AST + visitor keys, exactly as upstream's
// own tests/fixtures.test.ts does. `scopeManager` is always null upstream.
//
// Fixtures listed in test/parity.json `quarantine` are temporarily skipped while
// the port reaches parity; that list must be driven to empty.

import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { parseForESLint } from '../api.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(here, 'fixtures');
const parity = JSON.parse(readFileSync(join(here, 'parity.json'), 'utf8'));
const quarantine = new Set(parity.quarantine ?? []);

const fixtureNames = readdirSync(fixturesDir)
  .filter((name) => name.endsWith('.json'))
  .map((name) => name.replace(/\.json$/, ''))
  .sort();

const loadFixture = (name) =>
  JSON.parse(readFileSync(join(fixturesDir, `${name}.json`), 'utf8'));

describe('postgresql-eslint-parser fixtures', () => {
  it('has fixtures committed', () => {
    expect(fixtureNames.length).toBeGreaterThan(0);
  });

  it('quarantine lists only real fixtures', () => {
    const known = new Set(fixtureNames);
    for (const name of quarantine) {
      expect(known.has(name), `quarantined fixture "${name}" does not exist`).toBe(true);
    }
  });

  for (const name of fixtureNames) {
    const run = quarantine.has(name) ? it.skip : it;
    run(`parses ${name}`, () => {
      const fixture = loadFixture(name);
      const result = parseForESLint(fixture.input);
      expect(result.ast).toEqual(fixture.ast);
      expect(result.visitorKeys).toEqual(fixture.visitorKeys);
      expect(result.scopeManager).toBeNull();
    });
  }
});
