[package]
name = "oxlint-plugins-astro"
description = "Rust implementation of selected eslint-plugin-astro rules."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_parser.workspace = true
oxc_semantic.workspace = true
oxc_span.workspace = true
oxlint-plugins-carton.workspace = true

[lints]
workspace = true
