// Captures the upstream eslint-plugin-postgresql fixture suite straight from the
// vendored submodule and writes it to committed JSON fixtures, so the Vitest
// suite replays the real upstream cases and tracks behaviour as the submodule is
// bumped (oxc-style test syncing). Mirrors the other tools/tasks/sync-*-tests.ts
// scripts.
//
// Unlike the ESLint `RuleTester`-based plugins, eslint-plugin-postgresql authors
// its cases as on-disk fixtures: for each rule,
//   tests/fixtures/<rule>/valid/<name>.sql        (+ optional <name>.yaml: options)
//   tests/fixtures/<rule>/invalid/<name>.sql      (+ <name>.yaml: options/errors/output)
// The sibling `.yaml` files are generated by upstream's own RuleTester replay
// (`UPDATE_FIXTURES=true`) from the real plugin + parser, so they are the ground
// truth for expected diagnostics (messageId, message, 1-indexed line/column,
// endLine/endColumn) and autofix `output`.
//
// We read those files with the `yaml` parser (the same library upstream uses to
// write them) and emit one `npm/postgresql/test/fixtures/<rule>.json` per rule.
// Re-run with `pnpm run port:tests:postgresql`, then `vp fmt` the generated JSON.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parse as parseYaml } from 'yaml';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const UPSTREAM = join(ROOT, 'upstream', 'eslint-plugin-postgresql');
const FIXTURES_SRC = join(UPSTREAM, 'tests', 'fixtures');
const OUT_DIR = join(ROOT, 'npm', 'postgresql', 'test', 'fixtures');

type ExpectedError = {
  messageId?: string;
  message?: string;
  line?: number;
  column?: number;
  endLine?: number;
  endColumn?: number;
};

type FixtureMeta = {
  options?: unknown[];
  errors?: ExpectedError[];
  output?: string | null;
};

type Case = {
  name: string;
  code: string;
  options?: unknown[];
  errors?: ExpectedError[];
  output?: string | null;
};

function readText(path: string): string {
  // Trim matches upstream test-utils.ts (`readSql(...).trim()`) so that
  // `code` and the YAML-derived `output` share the same baseline (no trailing
  // newline), making autofix output comparisons exact.
  return readFileSync(path, 'utf8').replace(/\r\n/g, '\n').trim();
}

function readMeta(path: string): FixtureMeta {
  if (!existsSync(path)) {
    return {};
  }
  return (parseYaml(readFileSync(path, 'utf8')) ?? {}) as FixtureMeta;
}

function buildCases(ruleDir: string, kind: 'valid' | 'invalid'): Case[] {
  const dir = join(ruleDir, kind);
  if (!existsSync(dir)) {
    return [];
  }
  const sqlFiles = readdirSync(dir)
    .filter((name) => name.endsWith('.sql'))
    .sort();

  return sqlFiles.map((sqlFile) => {
    const base = sqlFile.slice(0, -'.sql'.length);
    const meta = readMeta(join(dir, `${base}.yaml`));
    const testCase: Case = { name: base, code: readText(join(dir, sqlFile)) };
    if (meta.options !== undefined) {
      testCase.options = meta.options;
    }
    if (kind === 'invalid') {
      testCase.errors = meta.errors ?? [];
      testCase.output = meta.output ?? null;
    }
    return testCase;
  });
}

function main(): void {
  if (!existsSync(FIXTURES_SRC)) {
    throw new Error(
      `Upstream fixtures not found at ${FIXTURES_SRC}. Run \`git submodule update --init upstream/eslint-plugin-postgresql\` first.`,
    );
  }

  const pkg = JSON.parse(readFileSync(join(UPSTREAM, 'package.json'), 'utf8')) as {
    name: string;
    version: string;
    license: string;
  };

  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const rules = readdirSync(FIXTURES_SRC)
    .filter((entry) => statSync(join(FIXTURES_SRC, entry)).isDirectory())
    .sort();

  let totalValid = 0;
  let totalInvalid = 0;

  for (const rule of rules) {
    const ruleDir = join(FIXTURES_SRC, rule);
    const valid = buildCases(ruleDir, 'valid');
    const invalid = buildCases(ruleDir, 'invalid');
    totalValid += valid.length;
    totalInvalid += invalid.length;

    const output = {
      __generated: {
        source: pkg.name,
        ref: `v${pkg.version}`,
        sourceDir: `tests/fixtures/${rule}`,
        license: pkg.license,
        tool: 'tools/tasks/sync-postgresql-tests.ts',
      },
      valid,
      invalid,
    };

    writeFileSync(join(OUT_DIR, `${rule}.json`), `${JSON.stringify(output, null, 2)}\n`);
  }

  console.log(
    `Captured ${rules.length} rules (${totalValid} valid, ${totalInvalid} invalid cases) into ${OUT_DIR}`,
  );
}

main();
