// Cross-checks `status.json` against `docs/port-targets/rules.json` (the canonical
// upstream rule inventory generated by `enumerate-port-rules.ts`) and adds an
// entry for every upstream rule that is not yet listed in `status.json`. Existing
// rule entries are preserved verbatim; only missing ones are appended with
// `status: 'pending'` and the default per-rule scaffold shape.
//
// Plugins missing from `status.json` entirely (e.g. eslint-plugin-react,
// typescript-eslint, eslint-plugin-sonarjs, eslint-plugin-postgresql,
// @angular-eslint/eslint-plugin-template) are bootstrapped here too, using the
// canonical port-target metadata. The corresponding `npm/<dir>/package.json`
// scaffolds live alongside this script and are checked by `verify-status.ts`.
//
// Re-run with `node tools/tasks/sync-status-from-port-targets.ts` whenever the
// upstream submodule pin or `tools/port-targets.json` changes. The script is
// idempotent.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type PortTargetManifest = {
  plugins: Array<{
    id: string;
    npm: string;
    repo: string;
    baselineVersion: string;
    license: string;
    expectedRuleCount: number;
    notes: string;
  }>;
};

type RulesInventory = {
  plugins: Array<{
    id: string;
    npm: string;
    repo: string;
    baselineVersion: string;
    license: string;
    rules: Array<{ name: string; description: string; docsUrl?: string; sonarKey?: string }>;
  }>;
};

type RuleStatus = {
  name: string;
  status: 'ported' | 'pending' | 'approximation' | 'sample';
  published: boolean;
  oxlintBuiltin: boolean;
  typeAware: boolean;
  rustCore: boolean;
  napi: boolean;
  tests: { insta: boolean; vitest: boolean; lsp: boolean; oxlintIntegration: boolean };
  notes: string;
};

type PluginStatus = {
  packageName: string;
  directory: string;
  version: string;
  published: boolean;
  publishedVersion: string | null;
  upstream: {
    package: string;
    version: string;
    repository: string;
    license: string;
  } | null;
  status: 'ported' | 'in-progress' | 'pending' | 'sample';
  typeAware: boolean;
  rules: RuleStatus[];
};

const ROOT = process.cwd();

// Mapping: port-target plugin id -> oxlint-plugins package directory + name.
// `npmDir` is the npm/<dir> path under the repo. `pkgName` is what status.json /
// package.json must agree on. Entries whose `pkgName` is null are skipped (they
// are upstream references with no rules of their own, e.g. typescript-eslint
// metapackage and the postgresql-eslint-parser package).
const PACKAGE_MAP: Record<
  string,
  | {
      pkgName: string;
      npmDir: string;
      shortName: string;
      typeAware?: boolean;
      sonar?: boolean;
    }
  | { pkgName: null }
> = {
  'eslint-plugin-eslint-comments': {
    pkgName: '@oxlint-plugins/oxlint-plugin-eslint-comments',
    npmDir: 'npm/eslint-comments',
    shortName: 'eslint-comments',
  },
  'eslint-plugin-functional': {
    pkgName: '@oxlint-plugins/oxlint-plugin-functional',
    npmDir: 'npm/functional',
    shortName: 'functional',
  },
  'eslint-plugin-regexp': {
    pkgName: '@oxlint-plugins/oxlint-plugin-regexp',
    npmDir: 'npm/regexp',
    shortName: 'regexp',
  },
  'eslint-plugin-security': {
    pkgName: '@oxlint-plugins/oxlint-plugin-security',
    npmDir: 'npm/security',
    shortName: 'security',
  },
  'eslint-plugin-simple-import-sort': {
    pkgName: '@oxlint-plugins/oxlint-plugin-simple-import-sort',
    npmDir: 'npm/simple-import-sort',
    shortName: 'simple-import-sort',
  },
  'eslint-plugin-e18e': {
    pkgName: '@oxlint-plugins/oxlint-plugin-e18e',
    npmDir: 'npm/e18e',
    shortName: 'e18e',
  },
  'eslint-plugin-mocha': {
    pkgName: '@oxlint-plugins/oxlint-plugin-mocha',
    npmDir: 'npm/mocha',
    shortName: 'mocha',
  },
  'eslint-plugin-unused-imports': {
    pkgName: '@oxlint-plugins/oxlint-plugin-unused-imports',
    npmDir: 'npm/unused-imports',
    shortName: 'unused-imports',
  },
  'eslint-plugin-testing-library': {
    pkgName: '@oxlint-plugins/oxlint-plugin-testing-library',
    npmDir: 'npm/testing-library',
    shortName: 'testing-library',
  },
  'eslint-plugin-perfectionist': {
    pkgName: '@oxlint-plugins/oxlint-plugin-perfectionist',
    npmDir: 'npm/perfectionist',
    shortName: 'perfectionist',
  },
  'eslint-plugin-cypress': {
    pkgName: '@oxlint-plugins/oxlint-plugin-cypress',
    npmDir: 'npm/cypress',
    shortName: 'cypress',
  },
  'eslint-plugin-playwright': {
    pkgName: '@oxlint-plugins/oxlint-plugin-playwright',
    npmDir: 'npm/playwright',
    shortName: 'playwright',
  },
  'angular-eslint-eslint-plugin': {
    pkgName: '@oxlint-plugins/oxlint-plugin-angular-eslint',
    npmDir: 'npm/angular-eslint',
    shortName: 'angular-eslint',
  },
  'angular-eslint-eslint-plugin-template': {
    pkgName: '@oxlint-plugins/oxlint-plugin-angular-eslint-template',
    npmDir: 'npm/angular-eslint-template',
    shortName: 'angular-eslint-template',
  },
  'typescript-eslint-eslint-plugin': {
    pkgName: '@oxlint-plugins/oxlint-plugin-typescript-eslint',
    npmDir: 'npm/typescript-eslint',
    shortName: 'typescript-eslint',
    typeAware: true,
  },
  'eslint-plugin-react': {
    pkgName: '@oxlint-plugins/oxlint-plugin-react',
    npmDir: 'npm/react',
    shortName: 'react',
  },
  'eslint-plugin-react-hooks': {
    pkgName: '@oxlint-plugins/oxlint-plugin-react-hooks',
    npmDir: 'npm/react-hooks',
    shortName: 'react-hooks',
  },
  'eslint-plugin-react-refresh': {
    pkgName: '@oxlint-plugins/oxlint-plugin-react-refresh',
    npmDir: 'npm/react-refresh',
    shortName: 'react-refresh',
  },
  'eslint-stylistic': {
    pkgName: '@oxlint-plugins/oxlint-plugin-stylistic',
    npmDir: 'npm/stylistic',
    shortName: 'stylistic',
  },
  'typescript-eslint': { pkgName: null },
  'eslint-plugin-sonarjs': {
    pkgName: '@oxlint-plugins/oxlint-plugin-sonarjs',
    npmDir: 'npm/sonarjs',
    shortName: 'sonarjs',
    sonar: true,
  },
  'eslint-plugin-storybook': {
    pkgName: '@oxlint-plugins/oxlint-plugin-storybook',
    npmDir: 'npm/storybook',
    shortName: 'storybook',
  },
  'unocss-eslint-plugin': {
    pkgName: '@oxlint-plugins/oxlint-plugin-unocss',
    npmDir: 'npm/unocss',
    shortName: 'unocss',
  },
  'eslint-json': {
    pkgName: '@oxlint-plugins/oxlint-plugin-eslint-json',
    npmDir: 'npm/eslint-json',
    shortName: 'eslint-json',
  },
  'eslint-markdown': {
    pkgName: '@oxlint-plugins/oxlint-plugin-eslint-markdown',
    npmDir: 'npm/eslint-markdown',
    shortName: 'eslint-markdown',
  },
  'eslint-plugin-postgresql': {
    pkgName: '@oxlint-plugins/oxlint-plugin-postgresql',
    npmDir: 'npm/postgresql',
    shortName: 'postgresql',
    typeAware: true,
  },
  'postgresql-eslint-parser': { pkgName: null },
};

const manifest = JSON.parse(
  readFileSync(join(ROOT, 'tools', 'port-targets.json'), 'utf8'),
) as PortTargetManifest;
const inventory = JSON.parse(
  readFileSync(join(ROOT, 'docs', 'port-targets', 'rules.json'), 'utf8'),
) as RulesInventory;
const status = JSON.parse(readFileSync(join(ROOT, 'status.json'), 'utf8')) as PluginStatus[];

const statusByPkg = new Map(status.map((entry) => [entry.packageName, entry]));
const inventoryById = new Map(inventory.plugins.map((entry) => [entry.id, entry]));

let appendedRules = 0;
let newPlugins = 0;

for (const target of manifest.plugins) {
  const mapping = PACKAGE_MAP[target.id];
  if (!mapping) {
    throw new Error(`Missing PACKAGE_MAP entry for port-target id '${target.id}'.`);
  }
  if (mapping.pkgName === null) continue;
  const upstreamRules = inventoryById.get(target.id)?.rules ?? [];
  if (upstreamRules.length === 0) continue;

  let existing = statusByPkg.get(mapping.pkgName);
  if (!existing) {
    existing = {
      packageName: mapping.pkgName,
      directory: mapping.npmDir,
      version: '0.0.0',
      published: false,
      publishedVersion: null,
      upstream: {
        package: manifestNpm(target.id),
        version: target.baselineVersion,
        repository: manifestRepo(target.id),
        license: manifestLicense(target.id),
      },
      status: 'pending',
      typeAware: mapping.typeAware ?? false,
      rules: [],
    };
    status.push(existing);
    statusByPkg.set(mapping.pkgName, existing);
    newPlugins += 1;
  }

  const ruleNames = new Set(existing.rules.map((rule) => rule.name));
  for (const rule of upstreamRules) {
    if (ruleNames.has(rule.name)) continue;
    const sonarSuffix = mapping.sonar && rule.sonarKey ? ` (Sonar key ${rule.sonarKey})` : '';
    const cleanRoomNote = mapping.sonar
      ? ' SonarJS upstream is LGPL-3.0; this port is clean-room from observed behavior only — never copy upstream source, fixtures, tests, or messages.'
      : '';
    existing.rules.push({
      name: rule.name,
      status: 'pending',
      published: false,
      oxlintBuiltin: false,
      typeAware: mapping.typeAware ?? false,
      rustCore: false,
      napi: false,
      tests: { insta: false, vitest: false, lsp: false, oxlintIntegration: false },
      notes: `Pending port of upstream rule ${rule.name}${sonarSuffix}.${cleanRoomNote}`,
    });
    appendedRules += 1;
  }

  if (existing.rules.length === 0) {
    throw new Error(`Plugin ${mapping.pkgName} has no rules after sync.`);
  }
}

// Stable order: keep existing position, then alphabetical for newcomers.
status.sort((a, b) => a.packageName.localeCompare(b.packageName));

writeFileSync(join(ROOT, 'status.json'), `${JSON.stringify(status, null, 2)}\n`);

console.log(`Appended ${appendedRules} pending rule(s) across ${newPlugins} new plugin(s).`);

function manifestNpm(id: string): string {
  return manifest.plugins.find((plugin) => plugin.id === id)?.npm ?? id;
}
function manifestRepo(id: string): string {
  return manifest.plugins.find((plugin) => plugin.id === id)?.repo ?? '';
}
function manifestLicense(id: string): string {
  return manifest.plugins.find((plugin) => plugin.id === id)?.license ?? 'MIT';
}
